### PR TITLE
Updated package.json for NPM release.

### PR DESCRIPTION
**Pull request by theantichris**

### CODE REVIEW

**Comment by samu** [comment]
@theantichris thanks!

**Comment by brunowego** [comment]
@theantichris please remove the postinstall too! Not needed for who uses npm.

**Comment by theantichris** [comment]
@brunowego Done.

**Comment by samu** [comment]
Hey, sorry, i completely forgot about this.

Removing the post install bower unfortunately makes the CI fail.

**Comment by samu** [comment]
Fixed it. Thanks for helping out!

**Pull request merged**
