### PR TITLE
Respect ng-if in header

### PR DESCRIPTION
**Pull request by PhilippSchreiber**
Hiding columns works only for the body. With this PR the ng-if gets duplicated to the th.

### CODE REVIEW

**Comment by samu** [comment]
Thanks, i'll review as soon as possible.

**Comment by samu** [comment]
@PhilippSchreiber thanks for the PR, and sorry for the long delay.

I'm not sure if i want to pull this though. The main problem is consistency: If the `ng-if` directive is replicated into the header, shouldn't this happen also for other directives, such as `ng-show` and `ng-hide`? In my opinion, if such functionality is provided, it should be provided on a consistent basis, in a more generic way. However i'm not sure if i want to introduce that level of complexity into this directive.

**Comment by slimovic** [comment]
@PhilippSchreiber **+1**

**Comment by samu** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
